# .github/workflows/main.yml
name: CI

on: [push]
permissions:
  contents: write
jobs:
  extract-openapi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Extract OpenAPI spec
        # working-directory: ./backend
        run: |
          cd backend/app
          python extract-openapi.py main:app --out openapi_generated.yaml


          
      # Do something with the generated spec here.
      # For example, validate that the committed spec matches the generated one.
      - name: Verify OpenAPI spec has been updated
        run: git diff --exit-code openapi.yaml openapi_generated.yaml
